import axios from 'axios';
import type { Subcommand } from '@sapphire/plugin-subcommands';
import { TextDisplayBuilder, SeparatorBuilder, SeparatorSpacingSize, FileBuilder, ContainerBuilder, MessageFlags, ButtonBuilder, ButtonStyle, ActionRowBuilder, type MessageActionRowComponentBuilder } from 'discord.js';

import { VirusTotalChatInputInteraction } from './types';

export async function chatInputVirusTotalDomain(_command: Subcommand, interaction: VirusTotalChatInputInteraction) {
	const domain = interaction.options.getString('name', true);
	const ephemeral = interaction.options.getBoolean('ephemeral') ?? true;

	await interaction.deferReply(ephemeral ? { flags: MessageFlags.Ephemeral } : undefined);

	try {
		const apiKey = process.env.VIRUSTOTAL_API_KEY;
		if (!apiKey) {
			await interaction.editReply({
				content: '❌ VirusTotal API key is not configured. Please contact an administrator.'
			});
			return;
		}

		const options = {
			method: 'GET',
			url: `https://www.virustotal.com/api/v3/domains/${domain}`,
			headers: {
				accept: 'application/json',
				'x-apikey': apiKey
			}
		};

		const response = await axios.request(options);
		const data = response.data;

		const stats = data.data.attributes.last_analysis_stats;
		const malicious = stats.malicious || 0;
		const suspicious = stats.suspicious || 0;
		const harmless = stats.harmless || 0;
		const undetected = stats.undetected || 0;

		let status = '🟢 **SAFE**';
		if (malicious > 0) {
			status = '🔴 **MALICIOUS**';
		} else if (suspicious > 0) {
			status = '🟡 **SUSPICIOUS**';
		}

		const attributes = data.data.attributes;
		const tld = attributes.tld || 'Unknown';
		const reputation = attributes.reputation || 0;
		const totalVotes = attributes.total_votes || {};
		const harmlessVotes = totalVotes.harmless || 0;
		const maliciousVotes = totalVotes.malicious || 0;
		const tags = attributes.tags || [];
		const categories = attributes.categories || {};

		const lastAnalysisDate = attributes.last_analysis_date
			? new Date(attributes.last_analysis_date * 1000).toLocaleDateString()
			: 'Unknown';

		const creationDate = attributes.creation_date
			? new Date(attributes.creation_date * 1000).toLocaleDateString()
			: 'Unknown';

		const results = attributes.last_analysis_results || {};
		const maliciousEngines = Object.entries(results)
			.filter(([_, result]: [string, any]) => result.category === 'malicious')
			.map(([engine]) => `${engine}`)
			.slice(0, 3);

		const popularityRanks = attributes.popularity_ranks || {};
		const rankInfo = Object.entries(popularityRanks)
			.map(([source, info]: [string, any]) => `${source}: #${info.rank}`)
			.join(', ') || 'Not ranked';

		const dnsRecords = attributes.last_dns_records || [];
		const dnsSummary = dnsRecords.slice(0, 5).map((record: any) =>
			`${record.type}: ${record.value}`
		).join('\n');

		const detailedReport = `
VIRUSTOTAL DOMAIN ANALYSIS REPORT
=================================

DOMAIN: ${domain}
TLD: ${tld}
CREATION DATE: ${creationDate}

REPUTATION SCORE: ${reputation}/100

LAST ANALYSIS DATE: ${lastAnalysisDate}

DETECTION SUMMARY:
- MALICIOUS: ${malicious} engines
- SUSPICIOUS: ${suspicious} engines
- CLEAN: ${harmless} engines
- UNDETECTED: ${undetected} engines

COMMUNITY VOTES:
- HARMLESS: ${harmlessVotes}
- MALICIOUS: ${maliciousVotes}

POPULARITY RANKS:
${rankInfo}

CATEGORIES: ${Object.keys(categories).length > 0 ? Object.keys(categories).join(', ') : 'None'}

TAGS: ${tags.length > 0 ? tags.join(', ') : 'None'}

MALICIOUS DETECTIONS:
${maliciousEngines.length > 0 ? maliciousEngines.map(engine => `- ${engine}`).join('\n') : 'None detected'}

WHOIS INFORMATION:
${attributes.whois || 'Not available'}

DNS RECORDS (Latest 10):
${dnsRecords.slice(0, 10).map((record: any) =>
			`${record.type} ${record.ttl || 'N/A'} ${record.value}${record.priority ? ` priority ${record.priority}` : ''}`
		).join('\n')}

LAST ANALYSIS RESULTS (Detailed):
${Object.entries(attributes.last_analysis_results || {})
				.map(([engine, result]: [string, any]) => `${engine}: ${result.category} (${result.result || 'N/A'})`)
				.join('\n')}

CERTIFICATE INFORMATION:
${attributes.last_https_certificate ? `
ISSUER: ${attributes.last_https_certificate.issuer?.CN || 'Unknown'}
SUBJECT: ${attributes.last_https_certificate.subject?.CN || 'Unknown'}
VALID FROM: ${attributes.last_https_certificate.validity?.not_before || 'Unknown'}
VALID TO: ${attributes.last_https_certificate.validity?.not_after || 'Unknown'}
THUMBPRINT: ${attributes.last_https_certificate.thumbprint || 'Unknown'}
SERIAL: ${attributes.last_https_certificate.serial_number || 'Unknown'}
` : 'No certificate information available'}

JARM FINGERPRINT: ${attributes.jarm || 'Not available'}

TOTAL VOTES: ${JSON.stringify(attributes.total_votes || {}, null, 2)}

Generated by Jasper Bot - ${new Date().toISOString()}
Powered by VirusTotal API
		`.trim();

		const components = [
			new ContainerBuilder()
				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent("## VirusTotal Domain Report")
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(`❓ **Security Status:** ${status}`)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(
						`🌐 **Domain Information**\n\n` +
						`• **Domain:** \`${domain}\`\n` +
						`• **TLD:** \`${tld}\`\n` +
						`• **Created:** \`${creationDate}\`\n` +
						`• **Reputation:** \`${reputation}/100\``
					)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(
						`📈 **Detection Summary:**\n\n` +
						`• **Malicious:** \`${malicious}\` engines\n` +
						`• **Suspicious:** \`${suspicious}\` engines\n` +
						`• **Clean:** \`${harmless}\` engines\n` +
						`• **Undetected:** \`${undetected}\` engines`
					)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(
						`🗳️ **Community Votes:**\n` +
						`\`${harmlessVotes}\` ✅ | \`${maliciousVotes}\` ❌\n\n` +
						`📅 **Last Analyzed:**\n` +
						`\`${lastAnalysisDate}\`\n\n` +
						`📊 **Popularity:**\n` +
						`\`${rankInfo}\`` +
						(Object.keys(categories).length > 0 ? `\n🏷️ **Categories:** \`${Object.keys(categories).join(', ')}\`` : '') +
						(tags.length > 0 ? `\n🏷️ **Tags:** \`${tags.join(', ')}\`` : '') +
						(maliciousEngines.length > 0 ? `\n⚠️ **Detected by:** \`${maliciousEngines.join(', ')}\`` : '')
					)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(
						`🔍 **DNS Records (Latest):**\n` +
						(dnsSummary ? `\`\`\`\n${dnsSummary}\n\`\`\`` : 'No DNS records available')
					)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addFileComponents(
					new FileBuilder().setURL(`attachment://virustotal-domain-${domain}.txt`)
				)

				.addActionRowComponents(
					new ActionRowBuilder<MessageActionRowComponentBuilder>().addComponents(
						new ButtonBuilder()
							.setStyle(ButtonStyle.Link)
							.setLabel("View Web Report")
							.setURL(`https://www.virustotal.com/gui/domain/${domain}`)
					)
				)
		];

		await interaction.editReply({
			files: [{
				attachment: Buffer.from(detailedReport),
				name: `virustotal-domain-${domain}.txt`
			}],
			components,
			flags: MessageFlags.IsComponentsV2
		});
	} catch (error) {
		console.error('VirusTotal API error:', error);
		await interaction.editReply({
			content: '❌ An error occurred while analyzing the domain. Please try again later.'
		});
	}
}