import type { Subcommand } from '@sapphire/plugin-subcommands';
import { MessageFlags } from 'discord.js';

import { VirusTotalChatInputInteraction } from './types';
import {
	validateApiKey,
	fetchVirusTotalData,
	getSecurityStatus,
	getMaliciousEngines,
	createReportComponents,
	handleVirusTotalError,
	formatUnixDate
} from './utils';
import { VIRUSTOTAL_CONFIG } from './constants';

export async function chatInputVirusTotalDomain(_command: Subcommand, interaction: VirusTotalChatInputInteraction) {
	const domain = interaction.options.getString('name', true);
	const ephemeral = interaction.options.getBoolean('ephemeral') ?? true;

	await interaction.deferReply(ephemeral ? { flags: MessageFlags.Ephemeral } : undefined);

	try {
		// Validate API key early
		validateApiKey();

		// Fetch data from VirusTotal
		const data = await fetchVirusTotalData<any>(`${VIRUSTOTAL_CONFIG.API.ENDPOINTS.DOMAINS}/${domain}`);

		const stats = data.data.attributes.last_analysis_stats;
		const attributes = data.data.attributes;
		const status = getSecurityStatus(stats);

		// Extract relevant information
		const tld = attributes.tld || 'Unknown';
		const reputation = attributes.reputation || 0;
		const totalVotes = attributes.total_votes || {};
		const harmlessVotes = totalVotes.harmless || 0;
		const maliciousVotes = totalVotes.malicious || 0;
		const tags = attributes.tags || [];
		const categories = attributes.categories || {};
		const lastAnalysisDate = formatUnixDate(attributes.last_analysis_date);
		const creationDate = formatUnixDate(attributes.creation_date);
		const maliciousEngines = getMaliciousEngines(attributes.last_analysis_results || {});

		const popularityRanks = attributes.popularity_ranks || {};
		const rankInfo =
			Object.entries(popularityRanks)
				.map(([source, info]: [string, any]) => `${source}: #${info.rank}`)
				.join(', ') || 'Not ranked';

		const dnsRecords = attributes.last_dns_records || [];
		const dnsSummary = dnsRecords
			.slice(0, 5)
			.map((record: any) => `${record.type}: ${record.value}`)
			.join('\n');

		// Build detailed report
		const detailedReport = `
VIRUSTOTAL DOMAIN ANALYSIS REPORT
=================================

DOMAIN: ${domain}
TLD: ${tld}
CREATION DATE: ${creationDate}

REPUTATION SCORE: ${reputation}/100

LAST ANALYSIS DATE: ${lastAnalysisDate}

DETECTION SUMMARY:
- MALICIOUS: ${stats.malicious || 0} engines
- SUSPICIOUS: ${stats.suspicious || 0} engines
- CLEAN: ${stats.harmless || 0} engines
- UNDETECTED: ${stats.undetected || 0} engines

COMMUNITY VOTES:
- HARMLESS: ${harmlessVotes}
- MALICIOUS: ${maliciousVotes}

POPULARITY RANKS:
${rankInfo}

CATEGORIES: ${Object.keys(categories).length > 0 ? Object.keys(categories).join(', ') : 'None'}

TAGS: ${tags.length > 0 ? tags.join(', ') : 'None'}

MALICIOUS DETECTIONS:
${maliciousEngines.length > 0 ? maliciousEngines.map((engine) => `- ${engine}`).join('\n') : 'None detected'}

WHOIS INFORMATION:
${attributes.whois || 'Not available'}

DNS RECORDS (Latest 10):
${dnsRecords
	.slice(0, 10)
	.map((record: any) => `${record.type} ${record.ttl || 'N/A'} ${record.value}${record.priority ? ` priority ${record.priority}` : ''}`)
	.join('\n')}

LAST ANALYSIS RESULTS (Detailed):
${Object.entries(attributes.last_analysis_results || {})
	.map(([engine, result]: [string, any]) => `${engine}: ${result.category} (${result.result || 'N/A'})`)
	.join('\n')}

CERTIFICATE INFORMATION:
${
	attributes.last_https_certificate
		? `
ISSUER: ${attributes.last_https_certificate.issuer?.CN || 'Unknown'}
SUBJECT: ${attributes.last_https_certificate.subject?.CN || 'Unknown'}
VALID FROM: ${attributes.last_https_certificate.validity?.not_before || 'Unknown'}
VALID TO: ${attributes.last_https_certificate.validity?.not_after || 'Unknown'}
THUMBPRINT: ${attributes.last_https_certificate.thumbprint || 'Unknown'}
SERIAL: ${attributes.last_https_certificate.serial_number || 'Unknown'}
`
		: 'No certificate information available'
}

JARM FINGERPRINT: ${attributes.jarm || 'Not available'}

TOTAL VOTES: ${JSON.stringify(attributes.total_votes || {}, null, 2)}

Generated by Jasper Bot - ${new Date().toISOString()}
Powered by VirusTotal API
		`.trim();

		// Build report sections
		const sections = [
			{
				title: '🌐 **Domain Information**',
				content:
					`• **Domain:** \`${domain}\`\n` +
					`• **TLD:** \`${tld}\`\n` +
					`• **Created:** \`${creationDate}\`\n` +
					`• **Reputation:** \`${reputation}/100\``
			},
			{
				title: '📈 **Detection Summary:**',
				content:
					`• **Malicious:** \`${stats.malicious || 0}\` engines\n` +
					`• **Suspicious:** \`${stats.suspicious || 0}\` engines\n` +
					`• **Clean:** \`${stats.harmless || 0}\` engines\n` +
					`• **Undetected:** \`${stats.undetected || 0}\` engines`
			},
			{
				title: '🗳️ **Community & Analysis**',
				content:
					`**Community Votes:**\n` +
					`\`${harmlessVotes}\` ✅ | \`${maliciousVotes}\` ❌\n\n` +
					`**Last Analyzed:**\n` +
					`\`${lastAnalysisDate}\`\n\n` +
					`**Popularity:**\n` +
					`\`${rankInfo}\`` +
					(Object.keys(categories).length > 0 ? `\n**Categories:** \`${Object.keys(categories).join(', ')}\`` : '') +
					(tags.length > 0 ? `\n**Tags:** \`${tags.join(', ')}\`` : '') +
					(maliciousEngines.length > 0 ? `\n⚠️ **Detected by:** \`${maliciousEngines.join(', ')}\`` : '')
			},
			{
				title: '🔍 **DNS Records (Latest):**',
				content: dnsSummary ? `\`\`\`\n${dnsSummary}\n\`\`\`` : 'No DNS records available'
			}
		];

		const components = createReportComponents(
			'VirusTotal Domain Report',
			status,
			sections,
			`https://www.virustotal.com/gui/domain/${domain}`,
			`virustotal-domain-${domain}.txt`
		);

		await interaction.editReply({
			files: [
				{
					attachment: Buffer.from(detailedReport),
					name: `virustotal-domain-${domain}.txt`
				}
			],
			components,
			flags: MessageFlags.IsComponentsV2
		});
	} catch (error) {
		const errorMessage = handleVirusTotalError(error, { domain });
		await interaction.editReply({ content: errorMessage });
	}
}
