import axios from 'axios';
import type { Subcommand } from '@sapphire/plugin-subcommands';
import { TextDisplayBuilder, SeparatorBuilder, SeparatorSpacingSize, FileBuilder, ContainerBuilder, MessageFlags, ButtonBuilder, ButtonStyle, ActionRowBuilder, type MessageActionRowComponentBuilder } from 'discord.js';

import { VirusTotalChatInputInteraction } from './types';

export async function chatInputVirusTotalIp(_command: Subcommand, interaction: VirusTotalChatInputInteraction) {
	const address = interaction.options.getString('address', true);
	const ephemeral = interaction.options.getBoolean('ephemeral') ?? true;

	await interaction.deferReply(ephemeral ? { flags: MessageFlags.Ephemeral } : undefined);

	try {
		const apiKey = process.env.VIRUSTOTAL_API_KEY;
		if (!apiKey) {
			await interaction.editReply({
				content: '❌ VirusTotal API key is not configured. Please contact an administrator.'
			});
			return;
		}

		const options = {
			method: 'GET',
			url: `https://www.virustotal.com/api/v3/ip_addresses/${address}`,
			headers: {
				accept: 'application/json',
				'x-apikey': apiKey
			}
		};

		const response = await axios.request(options);
		const data = response.data;

		const stats = data.data.attributes.last_analysis_stats;
		const malicious = stats.malicious || 0;
		const suspicious = stats.suspicious || 0;
		const harmless = stats.harmless || 0;
		const undetected = stats.undetected || 0;

		let status = '🟢 **SAFE**';
		if (malicious > 0) {
			status = '🔴 **MALICIOUS**';
		} else if (suspicious > 0) {
			status = '🟡 **SUSPICIOUS**';
		}

		const attributes = data.data.attributes;
		const country = attributes.country || 'Unknown';
		const asOwner = attributes.as_owner || 'Unknown';
		const reputation = attributes.reputation || 'Unknown';
		const totalVotes = attributes.total_votes || {};
		const harmlessVotes = totalVotes.harmless || 0;
		const maliciousVotes = totalVotes.malicious || 0;
		const tags = attributes.tags || [];

		const lastAnalysisDate = attributes.last_analysis_date
			? new Date(attributes.last_analysis_date * 1000).toLocaleDateString()
			: 'Unknown';

		const results = attributes.last_analysis_results || {};
		const maliciousEngines = Object.entries(results)
			.filter(([_, result]: [string, any]) => result.category === 'malicious')
			.map(([engine]) => `${engine}`)
			.slice(0, 3);

		const detailedReport = `
VIRUSTOTAL IP ANALYSIS REPORT
=============================

IP ADDRESS: ${address}
COUNTRY: ${attributes.country || 'Unknown'}
CONTINENT: ${attributes.continent || 'Unknown'}
AS OWNER: ${attributes.as_owner || 'Unknown'}
ASN: ${attributes.asn || 'Unknown'}
NETWORK: ${attributes.network || 'Unknown'}
REGIONAL INTERNET REGISTRY: ${attributes.regional_internet_registry || 'Unknown'}

REPUTATION SCORE: ${attributes.reputation || 0}/100

LAST ANALYSIS DATE: ${lastAnalysisDate}

DETECTION SUMMARY:
- MALICIOUS: ${malicious} engines
- SUSPICIOUS: ${suspicious} engines
- CLEAN: ${harmless} engines
- UNDETECTED: ${undetected} engines

COMMUNITY VOTES:
- HARMLESS: ${harmlessVotes}
- MALICIOUS: ${maliciousVotes}

TAGS: ${tags.length > 0 ? tags.join(', ') : 'None'}

MALICIOUS DETECTIONS:
${maliciousEngines.length > 0 ? maliciousEngines.map(engine => `- ${engine}`).join('\n') : 'None detected'}

WHOIS INFORMATION:
${attributes.whois || 'Not available'}

LAST ANALYSIS RESULTS (Detailed):
${Object.entries(attributes.last_analysis_results || {})
				.map(([engine, result]: [string, any]) => `${engine}: ${result.category} (${result.result || 'N/A'})`)
				.join('\n')}

CERTIFICATE INFORMATION:
${attributes.last_https_certificate ? `
ISSUER: ${attributes.last_https_certificate.issuer?.CN || 'Unknown'}
SUBJECT: ${attributes.last_https_certificate.subject?.CN || 'Unknown'}
VALID FROM: ${attributes.last_https_certificate.validity?.not_before || 'Unknown'}
VALID TO: ${attributes.last_https_certificate.validity?.not_after || 'Unknown'}
THUMBPRINT: ${attributes.last_https_certificate.thumbprint || 'Unknown'}
` : 'No certificate information available'}

JARM FINGERPRINT: ${attributes.jarm || 'Not available'}

TOTAL VOTES: ${JSON.stringify(attributes.total_votes || {}, null, 2)}

Generated by Jasper Bot - ${new Date().toISOString()}
Powered by VirusTotal API
		`.trim();

		const components = [
			new ContainerBuilder()
				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent("## VirusTotal IP Report")
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(`❓ **Security Status:** ${status}`)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(
						`📍 **General Information**\n\n` +
						`• **IP Address:** \`${address}\`\n` +
						`• **Country:** \`${country}\`\n` +
						`• **Owner:** \`${asOwner}\`\n` +
						`• **Reputation:** \`${reputation}/100\``
					)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(
						`📈 **Detection Summary:**\n\n` +
						`• **Malicious:** \`${malicious}\` engines\n` +
						`• **Suspicious:** \`${suspicious}\` engines\n` +
						`• **Clean:** \`${harmless}\` engines\n` +
						`• **Undetected:** \`${undetected}\` engines`
					)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addTextDisplayComponents(
					new TextDisplayBuilder().setContent(
						`🗳️ **Community Votes:**\n` +
						`\`${harmlessVotes}\` ✅ | \`${maliciousVotes}\` ❌\n\n` +
						`📅 **Last Analyzed:**\n` +
						`\`${lastAnalysisDate}\`` +
						(tags.length > 0 ? `\n🏷️ **Tags:** \`${tags.join(', ')}\`` : '') +
						(maliciousEngines.length > 0 ? `\n⚠️ **Detected by:** \`${maliciousEngines.join(', ')}\`` : '')
					)
				)
				.addSeparatorComponents(
					new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
				)

				.addFileComponents(
					new FileBuilder().setURL(`attachment://virustotal-ip-${address}.txt`)
				)

				.addActionRowComponents(
					new ActionRowBuilder<MessageActionRowComponentBuilder>().addComponents(
						new ButtonBuilder()
							.setStyle(ButtonStyle.Link)
							.setLabel("View Web Report")
							.setURL(`https://www.virustotal.com/gui/ip-address/${address}`)
					)
				)
		]; await interaction.editReply({
			files: [{
				attachment: Buffer.from(detailedReport),
				name: `virustotal-ip-${address}.txt`
			}],
			components,
			flags: MessageFlags.IsComponentsV2
		});
	} catch (error) {
		console.error('VirusTotal API error:', error);
		await interaction.editReply({
			content: '❌ An error occurred while analyzing the IP address. Please try again later.'
		});
	}
}