import axios from 'axios';
import type { Subcommand } from '@sapphire/plugin-subcommands';
import { MessageFlags } from 'discord.js';

import { VirusTotalChatInputInteraction } from './types';
import {
	validateApiKey,
	getSecurityStatus,
	getMaliciousEngines,
	createReportComponents,
	createProgressComponents,
	handleVirusTotalError,
	formatUnixDate
} from './utils';
import { VIRUSTOTAL_CONFIG } from './constants';

export async function chatInputVirusTotalUrl(_command: Subcommand, interaction: VirusTotalChatInputInteraction) {
	const url = interaction.options.getString('link', true);
	const ephemeral = interaction.options.getBoolean('ephemeral') ?? true;

	await interaction.deferReply(ephemeral ? { flags: MessageFlags.Ephemeral } : undefined);

	try {
		const apiKey = validateApiKey();

		// Step 1: Submit URL for analysis
		const submitOptions = {
			method: 'POST',
			url: `${VIRUSTOTAL_CONFIG.API.BASE_URL}${VIRUSTOTAL_CONFIG.API.ENDPOINTS.URLS}`,
			headers: {
				accept: 'application/json',
				'content-type': 'application/x-www-form-urlencoded',
				'x-apikey': apiKey
			},
			data: `url=${encodeURIComponent(url)}`
		};

		await axios.request(submitOptions); // Start analysis

		// Step 2: Notify user that scanning is in progress
		const progressComponents = createProgressComponents('VirusTotal URL Analysis', `Analyzing URL: \`${url}\``, false, 30);

		await interaction.editReply({
			components: progressComponents,
			flags: MessageFlags.IsComponentsV2
		});

		// Step 3: Wait 30 seconds for analysis to complete
		await new Promise((resolve) => setTimeout(resolve, 30000));

		// Step 4: Create URL ID and fetch results
		const urlId = Buffer.from(url).toString('base64url');

		const urlOptions = {
			method: 'GET',
			url: `${VIRUSTOTAL_CONFIG.API.BASE_URL}${VIRUSTOTAL_CONFIG.API.ENDPOINTS.URLS}/${urlId}`,
			headers: {
				accept: 'application/json',
				'x-apikey': apiKey
			}
		};

		const urlResponse = await axios.request(urlOptions);
		const urlData = urlResponse.data;

		const stats = urlData.data.attributes.last_analysis_stats;
		const attributes = urlData.data.attributes;
		const status = getSecurityStatus(stats);

		// Extract relevant information
		const totalVotes = attributes.total_votes || {};
		const harmlessVotes = totalVotes.harmless || 0;
		const maliciousVotes = totalVotes.malicious || 0;
		const tags = attributes.tags || [];
		const categories = attributes.categories || {};
		const title = attributes.title || 'No title detected';
		const httpCode = attributes.last_http_response_code || 'Unknown';
		const reputation = attributes.reputation || 0;
		const timesSubmitted = attributes.times_submitted || 1;
		const lastAnalysisDate = formatUnixDate(attributes.last_analysis_date);
		const maliciousEngines = getMaliciousEngines(attributes.last_analysis_results || {});

		// Build detailed report
		const detailedReport = `
VIRUSTOTAL URL ANALYSIS REPORT
==============================

URL: ${url}
TITLE: ${title}
HTTP STATUS: ${httpCode}

REPUTATION SCORE: ${reputation}/100
TIMES SUBMITTED: ${timesSubmitted}

LAST ANALYSIS DATE: ${lastAnalysisDate}

DETECTION SUMMARY:
- MALICIOUS: ${stats.malicious || 0} engines
- SUSPICIOUS: ${stats.suspicious || 0} engines
- CLEAN: ${stats.harmless || 0} engines
- UNDETECTED: ${stats.undetected || 0} engines

COMMUNITY VOTES:
- HARMLESS: ${harmlessVotes}
- MALICIOUS: ${maliciousVotes}

CATEGORIES: ${Object.keys(categories).length > 0 ? Object.keys(categories).join(', ') : 'None'}

TAGS: ${tags.length > 0 ? tags.join(', ') : 'None'}

MALICIOUS DETECTIONS:
${maliciousEngines.length > 0 ? maliciousEngines.map((engine) => `- ${engine}`).join('\n') : 'None detected'}

DETAILED ANALYSIS RESULTS:
${Object.entries(attributes.last_analysis_results || {})
	.map(([engine, result]: [string, any]) => `${engine}: ${result.category} (${result.result || 'N/A'})`)
	.join('\n')}

Generated by Jasper Bot - ${new Date().toISOString()}
Powered by VirusTotal API
		`.trim();

		// Build report sections
		const sections = [
			{
				title: '🔗 **URL Information**',
				content:
					`• **URL:** \`${url}\`\n` +
					`• **Title:** \`${title}\`\n` +
					`• **HTTP Status:** \`${httpCode}\`\n` +
					`• **Reputation:** \`${reputation}/100\``
			},
			{
				title: '📈 **Detection Summary:**',
				content:
					`• **Malicious:** \`${stats.malicious || 0}\` engines\n` +
					`• **Suspicious:** \`${stats.suspicious || 0}\` engines\n` +
					`• **Clean:** \`${stats.harmless || 0}\` engines\n` +
					`• **Undetected:** \`${stats.undetected || 0}\` engines`
			},
			{
				title: '🗳️ **Community & Analysis**',
				content:
					`**Community Votes:**\n` +
					`\`${harmlessVotes}\` ✅ | \`${maliciousVotes}\` ❌\n\n` +
					`**Last Analyzed:**\n` +
					`\`${lastAnalysisDate}\`\n\n` +
					`**Times Submitted:**\n` +
					`\`${timesSubmitted}\`` +
					(Object.keys(categories).length > 0 ? `\n**Categories:** \`${Object.keys(categories).join(', ')}\`` : '') +
					(tags.length > 0 ? `\n**Tags:** \`${tags.join(', ')}\`` : '') +
					(maliciousEngines.length > 0 ? `\n⚠️ **Detected by:** \`${maliciousEngines.join(', ')}\`` : '')
			}
		];

		const components = createReportComponents(
			'VirusTotal URL Report',
			status,
			sections,
			`https://www.virustotal.com/gui/url/${encodeURIComponent(url)}`,
			'virustotal-url-report.txt'
		);

		await interaction.editReply({
			files: [
				{
					attachment: Buffer.from(detailedReport),
					name: 'virustotal-url-report.txt'
				}
			],
			components,
			flags: MessageFlags.IsComponentsV2
		});
	} catch (error) {
		const errorMessage = handleVirusTotalError(error, { url });
		await interaction.editReply({ content: errorMessage });
	}
}
