import type { Subcommand } from '@sapphire/plugin-subcommands';
import { MessageFlags } from 'discord.js';

import { VirusTotalChatInputInteraction } from './types';
import {
	getSecurityStatus,
	getMaliciousEngines,
	createReportComponents,
	createProgressComponents,
	handleVirusTotalError,
	formatUnixDate
} from './utils';

// Handle /virustotal url subcommand: submit URL for scanning
export async function chatInputVirusTotalUrl(_command: Subcommand, interaction: VirusTotalChatInputInteraction) {
	const url = interaction.options.getString('link', true);
	const isEphemeral = interaction.options.getBoolean('ephemeral') ?? true;

	await interaction.deferReply({ flags: isEphemeral ? MessageFlags.Ephemeral : [] });

	try {
		const virusTotal = _command.container.virusTotalService;

		// Submit URL to VirusTotal for scanning
		await virusTotal.submitUrl(url);

		// Show progress indicator to user
		await showProgress(interaction, url);

		// Wait for analysis to complete (30 seconds)
		await new Promise((resolve) => setTimeout(resolve, 30000));

		// Fetch analysis results
		const urlId = virusTotal.getUrlId(url);
		const urlData = await virusTotal.fetchUrlById(urlId);

		const stats = urlData.data.attributes.last_analysis_stats;
		const attributes = urlData.data.attributes;
		const status = getSecurityStatus(stats);

		// Extract URL metadata
		const metadata = extractUrlMetadata(attributes);

		// Build detailed text report for download
		const detailedReport = buildDetailedReport(url, attributes, stats, metadata);

		// Build Discord component sections
		const sections = buildReportSections(url, stats, metadata);

		const components = createReportComponents(
			'VirusTotal URL Report',
			status,
			sections,
			`https://www.virustotal.com/gui/url/${encodeURIComponent(url)}`,
			'virustotal-url-report.txt'
		);

		await interaction.editReply({
			files: [
				{
					attachment: Buffer.from(detailedReport),
					name: 'virustotal-url-report.txt'
				}
			],
			components,
			flags: MessageFlags.IsComponentsV2
		});
	} catch (error) {
		const errorMessage = handleVirusTotalError(error, { url });
		await interaction.editReply({ content: errorMessage });
	}
}

// Show progress indicator during URL analysis
async function showProgress(interaction: VirusTotalChatInputInteraction, url: string): Promise<void> {
	const progressComponents = createProgressComponents('VirusTotal URL Analysis', `Analyzing URL: \`${url}\``, false, 30);

	await interaction.editReply({
		components: progressComponents,
		flags: MessageFlags.IsComponentsV2
	});
}

// Extract URL metadata from VirusTotal attributes
function extractUrlMetadata(attributes: any) {
	const totalVotes = attributes.total_votes || {};
	const maliciousEngines = getMaliciousEngines(attributes.last_analysis_results || {});

	return {
		title: attributes.title || 'No title detected',
		httpCode: attributes.last_http_response_code || 'Unknown',
		reputation: attributes.reputation || 0,
		timesSubmitted: attributes.times_submitted || 1,
		harmlessVotes: totalVotes.harmless || 0,
		maliciousVotes: totalVotes.malicious || 0,
		tags: attributes.tags || [],
		categories: attributes.categories || {},
		lastAnalysisDate: formatUnixDate(attributes.last_analysis_date),
		maliciousEngines
	};
}

// Build comprehensive text report for download
function buildDetailedReport(url: string, attributes: any, stats: any, metadata: any): string {
	return `
VIRUSTOTAL URL ANALYSIS REPORT
==============================

URL: ${url}
TITLE: ${metadata.title}
HTTP STATUS: ${metadata.httpCode}

REPUTATION SCORE: ${metadata.reputation}/100
TIMES SUBMITTED: ${metadata.timesSubmitted}

LAST ANALYSIS DATE: ${metadata.lastAnalysisDate}

DETECTION SUMMARY:
- MALICIOUS: ${stats.malicious || 0} engines
- SUSPICIOUS: ${stats.suspicious || 0} engines
- CLEAN: ${stats.harmless || 0} engines
- UNDETECTED: ${stats.undetected || 0} engines

COMMUNITY VOTES:
- HARMLESS: ${metadata.harmlessVotes}
- MALICIOUS: ${metadata.maliciousVotes}

CATEGORIES: ${Object.keys(metadata.categories).length > 0 ? Object.keys(metadata.categories).join(', ') : 'None'}

TAGS: ${metadata.tags.length > 0 ? metadata.tags.join(', ') : 'None'}

MALICIOUS DETECTIONS:
${metadata.maliciousEngines.length > 0 ? metadata.maliciousEngines.map((engine: string) => `- ${engine}`).join('\n') : 'None detected'}

DETAILED ANALYSIS RESULTS:
${Object.entries(attributes.last_analysis_results || {})
			.map(([engine, result]: [string, any]) => `${engine}: ${result.category} (${result.result || 'N/A'})`)
			.join('\n')}

Generated by Jasper Bot - ${new Date().toISOString()}
Powered by VirusTotal API
    `.trim();
}

// Build Discord component sections for display
function buildReportSections(url: string, stats: any, metadata: any): Array<{ title: string; content: string }> {
	return [
		{
			title: '🔗 **URL Information**',
			content:
				`• **URL:** \`${url}\`\n` +
				`• **Title:** \`${metadata.title}\`\n` +
				`• **HTTP Status:** \`${metadata.httpCode}\`\n` +
				`• **Reputation:** \`${metadata.reputation}/100\``
		},
		{
			title: '📈 **Detection Summary:**',
			content:
				`• **Malicious:** \`${stats.malicious || 0}\` engines\n` +
				`• **Suspicious:** \`${stats.suspicious || 0}\` engines\n` +
				`• **Clean:** \`${stats.harmless || 0}\` engines\n` +
				`• **Undetected:** \`${stats.undetected || 0}\` engines`
		},
		{
			title: '🗳️ **Community & Analysis**',
			content:
				`**Community Votes:**\n` +
				`\`${metadata.harmlessVotes}\` ✅ | \`${metadata.maliciousVotes}\` ❌\n\n` +
				`**Last Analyzed:**\n` +
				`\`${metadata.lastAnalysisDate}\`\n\n` +
				`**Times Submitted:**\n` +
				`\`${metadata.timesSubmitted}\`` +
				(Object.keys(metadata.categories).length > 0 ? `\n**Categories:** \`${Object.keys(metadata.categories).join(', ')}\`` : '') +
				(metadata.tags.length > 0 ? `\n**Tags:** \`${metadata.tags.join(', ')}\`` : '') +
				(metadata.maliciousEngines.length > 0 ? `\n⚠️ **Detected by:** \`${metadata.maliciousEngines.join(', ')}\`` : '')
		}
	];
}
